### ISSUE TITLE
Integrity checks fail

### ISSUE THREAD

**Issue by phacops** [frank604/Intel-DRM-Nightly#2]
After checking out your repo and running `makepkg -s`, this is what I have.

```
==> Making package: linux-drm-intel-nightly 20161030-1 (Fri Nov  4 09:15:08 PDT 2016)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating drm-intel git repo...
Fetching origin
  -> Found config
  -> Found config.x86_64
  -> Found linux-drm-intel-nightly.install
  -> Found linux-drm-intel-nightly.preset
==> ERROR: Integrity checks (sha256) differ in size from the source array.
```

Can you resign the files please?

**Comment by fszf** [comment]
I just pushed a commit updating package sums.  Please keep in mind that as we no longer need a patched version, it would be best to use the intel drm nightly from AUR.

This repo's purpose is to share any patches required 'on top of' the aur package.

**Comment by phacops** [comment]
Oh OK. So the nvme patches are in 4.9?

**Comment by fszf** [comment]
I must be getting old.  Sorry, no they didn't get in.  I'll have to modify the patches to apply.  Wait a few days hopefully.  I'll open an issue for that.  Thanks. #3

**Comment by fszf** [comment]
phacops can you pull latest, and recompile?
